name: Chrome Profile Selector

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v7
    - name: Install dependencies
      run: |
        sudo apt install zip python3-full python3-venv python-is-python3 -y
        python -m venv env
        source $GITHUB_WORKSPACE/env/bin/activate
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    - name: Compile application
      run: |
        pyinstaller --onedir --noconsole --add-data "icon.png;." --icon=icon.ico selector.py
    - name: Prepare release ZIP
      run: |
        zip -r $GITHUB_WORKSPACE/selector.zip $GITHUB_WORKSPACE/dist/selector/*.*
